name: Reusable Deploy
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output
        id: output
        run: | 
          echo "::set-output name=foo::bar"
          echo "Deploying code..."