name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the deployable artifact files'
        required: false
        default: dist
        type: string
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List all files
        run: ls
      - name: Output
        id: output
        run: | 
          echo "::set-output name=foo::bar"
          echo "Deploying code..."